"""
Generate a self-contained Kaggle submission notebook from a trained experiment.

Each src/ file is written as a %%writefile cell — fully human-readable in Kaggle's
notebook viewer, no encoding/decoding. The notebook is completely self-contained:
upload the single .ipynb file, attach the competition dataset, run all cells.

Usage (via run.py):
    python run.py configs/expNNN.yaml --notebook
"""
import json
import os

# src/ files for sklearn/GBM experiments
_SRC_FILES = [
    "src/__init__.py",
    "src/data.py",
    "src/features.py",
    "src/evaluate.py",
    "src/threshold.py",
    "src/logging_utils.py",
    "src/models/__init__.py",
    "src/models/linear.py",
    "src/train.py",
    "src/predict.py",
]

# src/ files for transformer experiments (import-dependency order)
_TRANSFORMER_SRC_FILES = [
    "src/__init__.py",
    "src/data.py",
    "src/features.py",
    "src/evaluate.py",
    "src/threshold.py",
    "src/logging_utils.py",
    "src/models/__init__.py",
    "src/models/transformer.py",
    "src/train_transformer.py",
    "src/predict.py",
]


def _cell(source: str, cell_type: str = "code") -> dict:
    lines = source.splitlines(keepends=True)
    # ensure final newline
    if lines and not lines[-1].endswith("\n"):
        lines[-1] += "\n"
    return {
        "cell_type": cell_type,
        "metadata": {},
        "source": lines,
        **({"outputs": [], "execution_count": None} if cell_type == "code" else {}),
    }


def _writefile_cell(rel_path: str) -> dict:
    """Return a code cell that writes rel_path to disk.
    Non-empty files use %%writefile (human-readable); empty files use open().write('').
    """
    with open(rel_path, "r", encoding="utf-8") as f:
        content = f.read()
    if not content.strip():
        # %%writefile errors on an empty cell body — use plain Python instead
        return _cell(f"open({rel_path!r}, 'w').close()  # empty init file\n")
    source = f"%%writefile {rel_path}\n{content}"
    return _cell(source)


def generate_notebook(exp_dir: str) -> str:
    """
    Generate experiments/<exp>/notebook.ipynb from a trained experiment dir.
    Raises FileNotFoundError if the model hasn't been trained yet.
    """
    model_path = os.path.join(exp_dir, "model.pkl")
    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"No trained model found at {model_path}. "
            "Run training first: python run.py configs/<name>.yaml --train"
        )

    config_path = os.path.join(exp_dir, "config.yaml")
    import yaml
    with open(config_path) as f:
        config = yaml.safe_load(f)

    exp_name = config.get("experiment_name", os.path.basename(exp_dir))
    notes    = config.get("notes", "")

    # ── Cell 0: Markdown header ──────────────────────────────────────────────
    header = [f"# {exp_name}\n"]
    if notes:
        header.append(f"\n**Notes:** {notes}\n")
    header += [
        "\nThis notebook was auto-generated by `src/notebook_gen.py`.\n",
        "Run all cells to train from scratch and produce `submission.csv`.\n",
    ]
    cell0 = _cell("".join(header), cell_type="markdown")

    # ── Cell 1: Install dependencies ─────────────────────────────────────────
    cell1 = _cell(
        "import subprocess, sys\n"
        "subprocess.check_call([\n"
        "    sys.executable, '-m', 'pip', 'install', '-q',\n"
        "    'pyyaml>=6.0', 'tqdm>=4.65', 'scikit-learn>=1.3',\n"
        "    'pandas>=2.0', 'numpy>=1.24', 'scipy>=1.11',\n"
        "])\n"
    )

    # ── Cells 2–N: %%writefile one cell per src/ file ────────────────────────
    # Create src/models/ dir before writing models files (%%writefile won't mkdir)
    mkdir_cell = _cell(
        "import os\n"
        "os.makedirs('src/models', exist_ok=True)\n"
    )

    src_cells = []
    for rel_path in _SRC_FILES:
        if os.path.exists(rel_path):
            src_cells.append(_writefile_cell(rel_path))

    # ── Config + training cell ────────────────────────────────────────────────
    with open(config_path) as f:
        config_str = f.read()
    config_dest = f"configs/{exp_name}.yaml"
    train_cell = _cell(
        "import os, shutil\n"
        "os.makedirs('configs', exist_ok=True)\n"
        f"open({config_dest!r}, 'w').write({json.dumps(config_str)})\n"
        "\n"
        "from src.train import run_training\n"
        "from src.predict import run_predict\n"
        f"exp_dir = run_training({config_dest!r})\n"
        "run_predict(exp_dir)\n"
        "\n"
        "# Kaggle requires submission.csv at the working directory root\n"
        "shutil.copy(os.path.join(exp_dir, 'submission.csv'), 'submission.csv')\n"
        "print('submission.csv copied to', os.getcwd())\n"
    )

    # ── Validation cell ───────────────────────────────────────────────────────
    validate_cell = _cell(
        "import pandas as pd, os\n"
        "sub_path = os.path.join(exp_dir, 'submission.csv')\n"
        "sub = pd.read_csv(sub_path)\n"
        "assert {'ID', 'target'}.issubset(sub.columns), f'Bad columns: {sub.columns.tolist()}'\n"
        "assert sub['target'].between(0, 6).all(), 'Targets out of range 0-6'\n"
        "print(f'submission.csv looks good: {len(sub)} rows')\n"
        "print(sub['target'].value_counts().sort_index().to_string())\n"
        "sub.head()\n"
    )

    cells = [cell0, cell1, mkdir_cell] + src_cells + [train_cell, validate_cell]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.10.0"},
        },
        "cells": cells,
    }

    out_path = os.path.join(exp_dir, "notebook.ipynb")
    with open(out_path, "w") as f:
        json.dump(notebook, f, indent=1)

    return out_path


def generate_inference_notebook(exp_dir: str, kaggle_dataset_slug: str) -> str:
    """
    Generate a fast inference-only Kaggle notebook.

    Loads the pre-trained model from a Kaggle dataset (no retraining),
    runs predict on the hidden test.csv, writes submission.csv.
    Completes in ~5 minutes vs 2-3h for a training notebook.

    Args:
        exp_dir: path to the trained experiment directory
        kaggle_dataset_slug: Kaggle dataset slug, e.g. 'username/exp010-bertimbau-es'
                             The dataset must contain the model/ files + thresholds.npy
    """
    model_dir = os.path.join(exp_dir, "model")
    if not os.path.isdir(model_dir):
        raise FileNotFoundError(f"No trained model at {model_dir}. Run --train first.")

    config_path = os.path.join(exp_dir, "config.yaml")
    import yaml
    with open(config_path) as f:
        config = yaml.safe_load(f)

    exp_name   = config.get("experiment_name", os.path.basename(exp_dir))
    notes      = config.get("notes", "")
    max_length = config.get("model", {}).get("max_length", 512)
    pretrained = config["model"]["pretrained"]

    # dataset mount path on Kaggle: /kaggle/input/<dataset-name>/
    dataset_name = kaggle_dataset_slug.split("/")[-1]
    dataset_mount = f"/kaggle/input/{dataset_name}"

    # ── Cell 0: header ───────────────────────────────────────────────────────
    cell0 = _cell("\n".join([
        f"# {exp_name} — inference only",
        "",
        f"**Notes:** {notes}" if notes else "",
        "",
        "Inference-only submission notebook — loads pre-trained weights, no retraining.",
        "Runs in ~5 minutes.",
        "",
        "## Setup checklist",
        "1. **Accelerator**: GPU T4×1 (or CPU — inference is fast)",
        "2. **Internet**: Off",
        "3. **Dataset**: attach `spr-2026-mammography-report-classification` competition data",
        f"4. **Model dataset**: attach `{kaggle_dataset_slug}` (your uploaded model weights)",
    ]), cell_type="markdown")

    # ── Cell 1: install deps ─────────────────────────────────────────────────
    cell1 = _cell(
        "import subprocess, sys\n"
        "subprocess.check_call([\n"
        "    sys.executable, '-m', 'pip', 'install', '-q',\n"
        "    'transformers>=4.40', 'sentencepiece>=0.1.99',\n"
        "    'pyyaml>=6.0', 'pandas>=2.0', 'numpy>=1.24',\n"
        "])\n"
    )

    # ── Cell 2: mkdir + write minimal src files needed for inference ─────────
    mkdir_cell = _cell(
        "import os\n"
        "os.makedirs('src/models', exist_ok=True)\n"
    )

    inference_src_files = [
        "src/__init__.py",
        "src/data.py",
        "src/features.py",
        "src/evaluate.py",
        "src/threshold.py",
        "src/logging_utils.py",
        "src/models/__init__.py",
        "src/models/transformer.py",
        "src/train_transformer.py",  # needed for _TextDataset
    ]
    src_cells = [_writefile_cell(p) for p in inference_src_files if os.path.exists(p)]

    # ── Cell 3: inference ────────────────────────────────────────────────────
    infer_cell = _cell(
        "import os\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import torch\n"
        "from torch.amp import autocast\n"
        "from torch.utils.data import DataLoader\n"
        "from src.data import load_test\n"
        "from src.features import clean_text\n"
        "from src.models.transformer import load_model as load_transformer\n"
        "from src.train_transformer import _TextDataset\n"
        "\n"
        "# Auto-detect uploaded model by scanning /kaggle/input/ for config.json\n"
        "def _find_uploaded_model():\n"
        "    import os\n"
        "    for root, dirs, files in os.walk('/kaggle/input'):\n"
        "        if 'config.json' in files and any(\n"
        "            f in files for f in ['model.safetensors', 'pytorch_model.bin']\n"
        "        ):\n"
        "            print(f'Found model at: {root}')\n"
        "            return root\n"
        "    raise FileNotFoundError('No model files found under /kaggle/input — did you attach the dataset?')\n"
        "\n"
        "DATASET_MOUNT = _find_uploaded_model()\n"
        f"MAX_LENGTH    = {max_length}\n"
        "\n"
        "# Load test data\n"
        "test = load_test()\n"
        "test['text'] = test['report'].apply(clean_text)\n"
        "print(f'Test rows: {len(test)}')\n"
        "\n"
        "# Load model from Kaggle dataset\n"
        "model, tokenizer = load_transformer(DATASET_MOUNT)\n"
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
        "print(f'Device: {device}')\n"
        "model = model.to(device).eval()\n"
        "\n"
        "# Tokenize and predict\n"
        "ds     = _TextDataset(test['text'].tolist(), tokenizer, MAX_LENGTH)\n"
        "loader = DataLoader(ds, batch_size=128, shuffle=False, num_workers=2)\n"
        "\n"
        "all_probs = []\n"
        "with torch.no_grad():\n"
        "    for batch in loader:\n"
        "        ids  = batch['input_ids'].to(device)\n"
        "        mask = batch['attention_mask'].to(device)\n"
        "        ttids = batch.get('token_type_ids')\n"
        "        kwargs = {'input_ids': ids, 'attention_mask': mask}\n"
        "        if ttids is not None:\n"
        "            kwargs['token_type_ids'] = ttids.to(device)\n"
        "        with autocast(device_type='cuda', enabled=torch.cuda.is_available()):\n"
        "            out = model(**kwargs)\n"
        "        all_probs.append(torch.softmax(out.logits.float(), dim=-1).cpu().numpy())\n"
        "\n"
        "prob_matrix = np.concatenate(all_probs, axis=0)\n"
        "\n"
        "# Apply saved threshold offsets if present\n"
        f"threshold_path = os.path.join(DATASET_MOUNT, 'thresholds.npy')\n"
        "if os.path.exists(threshold_path):\n"
        "    offsets = np.load(threshold_path)\n"
        "    preds = np.argmax(prob_matrix + offsets, axis=1)\n"
        "    print('Applied threshold offsets.')\n"
        "else:\n"
        "    preds = np.argmax(prob_matrix, axis=1)\n"
        "    print('No thresholds found — using argmax.')\n"
        "\n"
        "sub = pd.DataFrame({'ID': test['ID'], 'target': preds})\n"
        "sub.to_csv('submission.csv', index=False)\n"
        "print(f'submission.csv written: {len(sub)} rows')\n"
        "print(sub['target'].value_counts().sort_index().to_string())\n"
    )

    # ── Cell 4: validate ─────────────────────────────────────────────────────
    validate_cell = _cell(
        "import pandas as pd\n"
        "sub = pd.read_csv('submission.csv')\n"
        "assert {'ID', 'target'}.issubset(sub.columns)\n"
        "assert sub['target'].between(0, 6).all(), 'Targets out of range'\n"
        "print(f'submission.csv: {len(sub)} rows')\n"
        "sub.head()\n"
    )

    cells = [cell0, cell1, mkdir_cell] + src_cells + [infer_cell, validate_cell]
    out_path = os.path.join(exp_dir, "notebook_inference.ipynb")
    return _make_notebook(cells, out_path)


def generate_ensemble_inference_notebook(exp_dir: str) -> str:
    """
    Generate a Kaggle inference notebook for an ensemble experiment.

    Loads all component model weights from a single Kaggle dataset (upload all
    model/ dirs zipped together), runs inference on test.csv for each, averages
    probabilities, applies the ensemble thresholds, writes submission.csv.

    Upload instructions:
        kaggle datasets create -p <dir_with_all_model_subdirs> --dir-mode zip

    The dataset should contain one subdir per component, each with config.json
    and pytorch_model.bin / model.safetensors:
        upload_dir/
          exp023_bertimbau_dedup/   <- copy of experiments/exp023.../model/
          exp015a_bertimbau_seed7/
          exp015b_bertimbau_seed13/
          exp015c_bertimbau_seed21/
          thresholds.npy            <- copy of this ensemble's thresholds.npy
    """
    import yaml

    ensemble_cfg_path = os.path.join(exp_dir, "ensemble_config.json")
    if not os.path.exists(ensemble_cfg_path):
        raise FileNotFoundError(f"No ensemble_config.json at {ensemble_cfg_path}")

    with open(ensemble_cfg_path) as f:
        ens_cfg = json.load(f)

    components = ens_cfg["components"]
    weights    = ens_cfg.get("weights", [1 / len(components)] * len(components))
    exp_name   = ens_cfg["experiment_name"]

    # Recursively resolve nested ensembles into flat (leaf_model, effective_weight) pairs
    def _resolve(comps, wts):
        flat = []
        for comp, w in zip(comps, wts):
            sub_cfg_path = os.path.join("experiments", comp, "ensemble_config.json")
            if os.path.exists(sub_cfg_path):
                with open(sub_cfg_path) as f:
                    sub = json.load(f)
                sub_comps = sub["components"]
                sub_wts = sub.get("weights", [1 / len(sub_comps)] * len(sub_comps))
                flat.extend(_resolve(sub_comps, [sw * w for sw in sub_wts]))
            else:
                flat.append((comp, w))
        return flat

    resolved   = _resolve(components, weights)
    components = [r[0] for r in resolved]
    weights    = [r[1] for r in resolved]

    # Verify all component model dirs exist
    for comp in components:
        model_dir = os.path.join("experiments", comp, "model")
        if not os.path.isdir(model_dir):
            raise FileNotFoundError(f"Component model not found: {model_dir}")

    # Read max_length from first component config
    first_cfg_path = os.path.join("experiments", components[0], "config.yaml")
    with open(first_cfg_path) as f:
        first_cfg = yaml.safe_load(f)
    max_length = first_cfg.get("model", {}).get("max_length", 256)
    pretrained = first_cfg["model"]["pretrained"]

    # ── Cell 0: markdown header ──────────────────────────────────────────────
    cell0 = _cell("\n".join([
        f"# {exp_name} — ensemble inference",
        "",
        f"**Components ({len(components)} models):** " + ", ".join(components),
        f"**Weights:** {weights}",
        "",
        "Inference-only notebook — loads pre-trained weights for each component model,",
        "averages probability outputs, applies tuned thresholds, writes `submission.csv`.",
        "Runs in ~10–15 minutes.",
        "",
        "## Setup checklist",
        "1. **Accelerator**: GPU T4×1 (or CPU)",
        "2. **Internet**: Off",
        "3. **Competition dataset**: attach `spr-2026-mammography-report-classification`",
        f"4. **Model dataset**: upload all component model dirs + thresholds.npy as one",
        f"   Kaggle dataset (see `scripts/upload_ensemble_weights.sh` for instructions)",
    ]), cell_type="markdown")

    # ── Cell 1: install deps ─────────────────────────────────────────────────
    cell1 = _cell(
        "import subprocess, sys\n"
        "subprocess.check_call([\n"
        "    sys.executable, '-m', 'pip', 'install', '-q',\n"
        "    'transformers>=4.40', 'sentencepiece>=0.1.99',\n"
        "    'pyyaml>=6.0', 'pandas>=2.0', 'numpy>=1.24',\n"
        "])\n"
    )

    # ── Cell 2: mkdir + src files ────────────────────────────────────────────
    mkdir_cell = _cell(
        "import os\n"
        "os.makedirs('src/models', exist_ok=True)\n"
    )

    inference_src_files = [
        "src/__init__.py",
        "src/data.py",
        "src/features.py",
        "src/evaluate.py",
        "src/threshold.py",
        "src/logging_utils.py",
        "src/models/__init__.py",
        "src/models/transformer.py",
        "src/train_transformer.py",
    ]
    src_cells = [_writefile_cell(p) for p in inference_src_files if os.path.exists(p)]

    # ── Cell 3: ensemble inference ───────────────────────────────────────────
    components_repr = repr(components)
    weights_repr    = repr(weights)

    infer_cell = _cell(
        "import os\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import torch\n"
        "from torch.amp import autocast\n"
        "from torch.utils.data import DataLoader\n"
        "from transformers import AutoModelForSequenceClassification, AutoTokenizer\n"
        "from src.data import load_test\n"
        "from src.features import clean_text\n"
        "from src.train_transformer import _TextDataset\n"
        "\n"
        "COMPONENTS   = " + components_repr + "\n"
        "WEIGHTS      = " + weights_repr + "\n"
        f"MAX_LENGTH   = {max_length}\n"
        "\n"
        "# Find the dataset dir containing all component model subdirs\n"
        "def _find_dataset_root():\n"
        "    for root, dirs, files in os.walk('/kaggle/input'):\n"
        "        if 'thresholds.npy' in files:\n"
        "            print(f'Found ensemble dataset at: {root}')\n"
        "            return root\n"
        "    raise FileNotFoundError('thresholds.npy not found — did you attach the model dataset?')\n"
        "\n"
        "DATASET_ROOT = _find_dataset_root()\n"
        "\n"
        "# Load test data once\n"
        "test = load_test()\n"
        "test['text'] = test['report'].apply(clean_text)\n"
        "print(f'Test rows: {len(test)}')\n"
        "\n"
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
        "print(f'Device: {device}')\n"
        "\n"
        "def _load_model_via_symlink(src_dir, idx):\n"
        "    \"\"\"Load a HuggingFace model from a deep path using a short symlink.\n"
        "    Newer huggingface_hub rejects paths with >1 slash as invalid repo_ids.\n"
        "    A short relative symlink has 0 slashes and bypasses this validation.\n"
        "    \"\"\"\n"
        "    link = f'_mdl{idx}'\n"
        "    if os.path.lexists(link):\n"
        "        os.unlink(link)\n"
        "    os.symlink(os.path.abspath(src_dir), os.path.abspath(link))\n"
        "    try:\n"
        "        tok   = AutoTokenizer.from_pretrained(link, local_files_only=True)\n"
        "        model = AutoModelForSequenceClassification.from_pretrained(\n"
        "            link, local_files_only=True)\n"
        "    finally:\n"
        "        os.unlink(link)\n"
        "    return model, tok\n"
        "\n"
        "# Run inference for each component model and accumulate weighted probs\n"
        "os.chdir('/kaggle/working')  # ensure relative symlinks resolve correctly\n"
        "ensemble_probs = None\n"
        "for i, (comp, w) in enumerate(zip(COMPONENTS, WEIGHTS)):\n"
        "    # Dataset was uploaded with model files directly inside comp/ (no model/ subdir)\n"
        "    model_path = os.path.join(DATASET_ROOT, comp)\n"
        "    if not os.path.isdir(model_path):\n"
        "        candidates = [d for d, _, fs in os.walk(DATASET_ROOT)\n"
        "                      if 'config.json' in fs and comp in d]\n"
        "        if not candidates:\n"
        "            raise FileNotFoundError(f'Model dir for {comp} not found under {DATASET_ROOT}')\n"
        "        model_path = candidates[0]\n"
        "    print(f'Loading {comp} from {model_path} (weight={w})')\n"
        "    model, tokenizer = _load_model_via_symlink(model_path, i)\n"
        "    model = model.to(device).eval()\n"
        "\n"
        "    ds     = _TextDataset(test['text'].tolist(), tokenizer, MAX_LENGTH)\n"
        "    loader = DataLoader(ds, batch_size=128, shuffle=False, num_workers=2)\n"
        "\n"
        "    all_probs = []\n"
        "    with torch.no_grad():\n"
        "        for batch in loader:\n"
        "            ids  = batch['input_ids'].to(device)\n"
        "            mask = batch['attention_mask'].to(device)\n"
        "            ttids = batch.get('token_type_ids')\n"
        "            kwargs = {'input_ids': ids, 'attention_mask': mask}\n"
        "            if ttids is not None:\n"
        "                kwargs['token_type_ids'] = ttids.to(device)\n"
        "            with autocast(device_type='cuda', enabled=torch.cuda.is_available()):\n"
        "                out = model(**kwargs)\n"
        "            all_probs.append(torch.softmax(out.logits.float(), dim=-1).cpu().numpy())\n"
        "\n"
        "    comp_probs = np.concatenate(all_probs, axis=0)\n"
        "    ensemble_probs = comp_probs * w if ensemble_probs is None else ensemble_probs + comp_probs * w\n"
        "    del model\n"
        "    torch.cuda.empty_cache()\n"
        "    print(f'  done — shape {comp_probs.shape}')\n"
        "\n"
        "# Apply saved threshold offsets\n"
        "threshold_path = os.path.join(DATASET_ROOT, 'thresholds.npy')\n"
        "offsets = np.load(threshold_path)\n"
        "preds = np.argmax(ensemble_probs + offsets, axis=1)\n"
        "print(f'Applied threshold offsets from {threshold_path}')\n"
        "\n"
        "sub = pd.DataFrame({'ID': test['ID'], 'target': preds})\n"
        "sub.to_csv('submission.csv', index=False)\n"
        "print(f'submission.csv written: {len(sub)} rows')\n"
        "print(sub['target'].value_counts().sort_index().to_string())\n"
    )

    # ── Cell 4: validate ─────────────────────────────────────────────────────
    validate_cell = _cell(
        "import pandas as pd\n"
        "sub = pd.read_csv('submission.csv')\n"
        "assert {'ID', 'target'}.issubset(sub.columns)\n"
        "assert sub['target'].between(0, 6).all(), 'Targets out of range'\n"
        "print(f'submission.csv: {len(sub)} rows')\n"
        "sub.head()\n"
    )

    cells = [cell0, cell1, mkdir_cell] + src_cells + [infer_cell, validate_cell]
    out_path = os.path.join(exp_dir, "notebook_inference.ipynb")
    return _make_notebook(cells, out_path)


def generate_rerank_inference_notebook(rerank_exp_dir: str) -> str:
    """
    Generate a Kaggle inference notebook for a specialist-rerank experiment.

    The pipeline:
      1. Load each base-ensemble component model, run inference, average probs.
      2. Load each specialist model, apply soft gated reranking.
      3. Apply tuned threshold offsets.
      4. Write submission.csv.

    Upload a single Kaggle dataset containing one subdir per model + thresholds.npy:
        upload_dir/
          <base_comp_0>/          <- copy of experiments/<comp>/model/ contents
          <base_comp_1>/
          ...
          <spec023_name>/
          <spec456_name>/
          thresholds.npy          <- copy of experiments/<rerank_exp>/thresholds.npy
    """
    import yaml

    rerank_cfg_path = os.path.join(rerank_exp_dir, "rerank_config.json")
    if not os.path.exists(rerank_cfg_path):
        raise FileNotFoundError(f"No rerank_config.json at {rerank_cfg_path}")
    with open(rerank_cfg_path) as f:
        rk = json.load(f)

    base_exp   = rk["base"]
    spec023    = rk.get("spec023")
    spec456    = rk.get("spec456")
    alpha023   = rk.get("alpha023", 0.5)
    alpha456   = rk.get("alpha456", 0.5)
    exp_name   = rk["experiment_name"]

    # Resolve base ensemble components
    base_dir = os.path.join("experiments", base_exp)
    ens_cfg_path = os.path.join(base_dir, "ensemble_config.json")
    if not os.path.exists(ens_cfg_path):
        raise FileNotFoundError(f"Base experiment {base_exp} has no ensemble_config.json")
    with open(ens_cfg_path) as f:
        ens_cfg = json.load(f)
    base_components = ens_cfg["components"]
    base_weights    = ens_cfg.get("weights", [1 / len(base_components)] * len(base_components))

    # Read config from first base component
    first_cfg_path = os.path.join("experiments", base_components[0], "config.yaml")
    with open(first_cfg_path) as f:
        first_cfg = yaml.safe_load(f)
    max_length = first_cfg.get("model", {}).get("max_length", 256)

    all_model_dirs = base_components + ([spec023] if spec023 else []) + ([spec456] if spec456 else [])
    for m in all_model_dirs:
        if not os.path.isdir(os.path.join("experiments", m, "model")):
            raise FileNotFoundError(f"Model dir missing: experiments/{m}/model/")

    # Read specialist class maps (local index → global class label)
    def _read_local_to_global(exp_name):
        p = os.path.join("experiments", exp_name, "class_map.json")
        if not os.path.exists(p):
            return None
        with open(p) as f:
            cm = json.load(f)
        return {int(k): int(v) for k, v in cm["local_to_global"].items()}

    spec023_l2g = _read_local_to_global(spec023) if spec023 else None
    spec456_l2g = _read_local_to_global(spec456) if spec456 else None

    # ── Cell 0: header ───────────────────────────────────────────────────────
    cell0 = _cell("\n".join([
        f"# {exp_name} — specialist rerank inference",
        "",
        f"**Base ensemble:** {base_exp} ({len(base_components)} models)",
        f"**Specialists:** {spec023} (α={alpha023}), {spec456} (α={alpha456})",
        "",
        "Inference pipeline: average base model probs → soft specialist rerank → threshold tuning offsets → submission.csv",
        "Runtime: ~15–20 min on GPU T4.",
        "",
        "## Setup checklist",
        "1. **Accelerator**: GPU T4×1",
        "2. **Internet**: Off",
        "3. **Competition dataset**: attach `spr-2026-mammography-report-classification`",
        "4. **Model dataset**: upload all 6 model dirs + thresholds.npy as one Kaggle dataset",
        "   (see the prep script output for exact directory layout)",
    ]), cell_type="markdown")

    # ── Cell 1: install deps ─────────────────────────────────────────────────
    cell1 = _cell(
        "import subprocess, sys\n"
        "subprocess.check_call([\n"
        "    sys.executable, '-m', 'pip', 'install', '-q',\n"
        "    'transformers>=4.40', 'sentencepiece>=0.1.99',\n"
        "    'pyyaml>=6.0', 'pandas>=2.0', 'numpy>=1.24',\n"
        "])\n"
    )

    # ── Cell 2: src files ────────────────────────────────────────────────────
    mkdir_cell = _cell("import os\nos.makedirs('src/models', exist_ok=True)\n")
    inference_src_files = [
        "src/__init__.py", "src/data.py", "src/features.py",
        "src/evaluate.py", "src/threshold.py", "src/logging_utils.py",
        "src/models/__init__.py", "src/models/transformer.py",
        "src/train_transformer.py",
    ]
    src_cells = [_writefile_cell(p) for p in inference_src_files if os.path.exists(p)]

    # ── Cell 3: inference + rerank ───────────────────────────────────────────
    base_comps_repr   = repr(base_components)
    base_weights_repr = repr(base_weights)
    spec023_repr      = repr(spec023)
    spec456_repr      = repr(spec456)
    spec023_l2g_repr  = repr(spec023_l2g)
    spec456_l2g_repr  = repr(spec456_l2g)

    infer_code = (
        "import os, numpy as np, pandas as pd, torch\n"
        "from torch.amp import autocast\n"
        "from torch.utils.data import DataLoader\n"
        "from transformers import AutoModelForSequenceClassification, AutoTokenizer\n"
        "from src.data import load_test\n"
        "from src.features import clean_text\n"
        "from src.train_transformer import _TextDataset\n"
        "\n"
        f"BASE_COMPONENTS  = {base_comps_repr}\n"
        f"BASE_WEIGHTS     = {base_weights_repr}\n"
        f"SPEC023          = {spec023_repr}\n"
        f"SPEC456          = {spec456_repr}\n"
        f"SPEC023_L2G      = {spec023_l2g_repr}\n"
        f"SPEC456_L2G      = {spec456_l2g_repr}\n"
        f"ALPHA023         = {alpha023}\n"
        f"ALPHA456         = {alpha456}\n"
        f"MAX_LENGTH       = {max_length}\n"
        "N_CLASSES        = 7\n"
        "\n"
        "def _find_dataset_root():\n"
        "    for root, dirs, files in os.walk('/kaggle/input'):\n"
        "        if 'thresholds.npy' in files:\n"
        "            print(f'Dataset root: {root}'); return root\n"
        "    raise FileNotFoundError('thresholds.npy not found — attach the model dataset')\n"
        "\n"
        "def _load_model(dataset_root, name, idx):\n"
        "    src_dir = os.path.join(dataset_root, name)\n"
        "    if not os.path.isdir(src_dir):\n"
        "        cands = [d for d, _, fs in os.walk(dataset_root) if 'config.json' in fs and name in d]\n"
        "        if not cands: raise FileNotFoundError(f'{name} not found under {dataset_root}')\n"
        "        src_dir = cands[0]\n"
        "    link = f'_mdl{idx}'\n"
        "    if os.path.lexists(link): os.unlink(link)\n"
        "    os.symlink(os.path.abspath(src_dir), os.path.abspath(link))\n"
        "    try:\n"
        "        tok = AutoTokenizer.from_pretrained(link, local_files_only=True)\n"
        "        mdl = AutoModelForSequenceClassification.from_pretrained(link, local_files_only=True)\n"
        "    finally:\n"
        "        os.unlink(link)\n"
        "    return mdl, tok\n"
        "\n"
        "def _run_inference(model, tokenizer, texts, device):\n"
        "    ds = _TextDataset(texts, tokenizer, MAX_LENGTH)\n"
        "    loader = DataLoader(ds, batch_size=128, shuffle=False, num_workers=2)\n"
        "    all_probs = []\n"
        "    with torch.no_grad():\n"
        "        for batch in loader:\n"
        "            ids  = batch['input_ids'].to(device)\n"
        "            mask = batch['attention_mask'].to(device)\n"
        "            ttids = batch.get('token_type_ids')\n"
        "            kwargs = {'input_ids': ids, 'attention_mask': mask}\n"
        "            if ttids is not None: kwargs['token_type_ids'] = ttids.to(device)\n"
        "            with autocast(device_type='cuda', enabled=torch.cuda.is_available()):\n"
        "                out = model(**kwargs)\n"
        "            all_probs.append(torch.softmax(out.logits.float(), dim=-1).cpu().numpy())\n"
        "    return np.concatenate(all_probs, axis=0)\n"
        "\n"
        "def _expand_spec_probs(local_probs, local_to_global):\n"
        "    \"\"\"Expand (N, K) specialist output to (N, 7) using local→global class map.\"\"\"\n"
        "    n = local_probs.shape[0]\n"
        "    out = np.zeros((n, N_CLASSES), dtype=float)\n"
        "    for local_idx, global_idx in local_to_global.items():\n"
        "        out[:, global_idx] = local_probs[:, local_idx]\n"
        "    return out\n"
        "\n"
        "def _renorm_group(probs, group):\n"
        "    sub = probs[:, group].copy()\n"
        "    denom = sub.sum(axis=1, keepdims=True)\n"
        "    denom = np.where(denom <= 0, 1.0, denom)\n"
        "    return sub / denom\n"
        "\n"
        "def _blend_group(base_probs, spec_probs, group, alpha):\n"
        "    out = base_probs.copy()\n"
        "    base_mass = base_probs[:, group].sum(axis=1, keepdims=True)\n"
        "    blended = (1 - alpha) * _renorm_group(base_probs, group) + alpha * _renorm_group(spec_probs, group)\n"
        "    out[:, group] = blended * base_mass\n"
        "    return out\n"
        "\n"
        "os.chdir('/kaggle/working')\n"
        "DATASET_ROOT = _find_dataset_root()\n"
        "test = load_test()\n"
        "test['text'] = test['report'].apply(clean_text)\n"
        "print(f'Test rows: {len(test)}')\n"
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
        "print(f'Device: {device}')\n"
        "\n"
        "# Step 1: average base model probs\n"
        "base_probs = None\n"
        "for i, (comp, w) in enumerate(zip(BASE_COMPONENTS, BASE_WEIGHTS)):\n"
        "    print(f'Base model {i+1}/{len(BASE_COMPONENTS)}: {comp}')\n"
        "    mdl, tok = _load_model(DATASET_ROOT, comp, i)\n"
        "    mdl = mdl.to(device).eval()\n"
        "    p = _run_inference(mdl, tok, test['text'].tolist(), device)\n"
        "    base_probs = p * w if base_probs is None else base_probs + p * w\n"
        "    del mdl; torch.cuda.empty_cache()\n"
        "print(f'Base ensemble shape: {base_probs.shape}')\n"
        "\n"
        "# Step 2: specialist reranking\n"
        "probs = base_probs.copy()\n"
        "n_base = len(BASE_COMPONENTS)\n"
        "if SPEC023:\n"
        "    print(f'Loading spec023: {SPEC023}')\n"
        "    mdl, tok = _load_model(DATASET_ROOT, SPEC023, n_base)\n"
        "    mdl = mdl.to(device).eval()\n"
        "    spec023_local = _run_inference(mdl, tok, test['text'].tolist(), device)\n"
        "    spec023_probs = _expand_spec_probs(spec023_local, SPEC023_L2G)\n"
        "    del mdl; torch.cuda.empty_cache()\n"
        "    top2 = np.argsort(probs, axis=1)[:, -2:]\n"
        "    gate023 = np.isin(top2, [0, 2, 3]).all(axis=1)\n"
        "    print(f'  gate023 activates on {gate023.sum()} rows')\n"
        "    blended = _blend_group(probs, spec023_probs, [0, 2, 3], ALPHA023)\n"
        "    probs[gate023] = blended[gate023]\n"
        "if SPEC456:\n"
        "    print(f'Loading spec456: {SPEC456}')\n"
        "    mdl, tok = _load_model(DATASET_ROOT, SPEC456, n_base + 1)\n"
        "    mdl = mdl.to(device).eval()\n"
        "    spec456_local = _run_inference(mdl, tok, test['text'].tolist(), device)\n"
        "    spec456_probs = _expand_spec_probs(spec456_local, SPEC456_L2G)\n"
        "    del mdl; torch.cuda.empty_cache()\n"
        "    top2 = np.argsort(probs, axis=1)[:, -2:]\n"
        "    gate456 = np.isin(top2, [4, 5, 6]).all(axis=1)\n"
        "    print(f'  gate456 activates on {gate456.sum()} rows')\n"
        "    blended = _blend_group(probs, spec456_probs, [4, 5, 6], ALPHA456)\n"
        "    probs[gate456] = blended[gate456]\n"
        "\n"
        "# Step 3: apply tuned threshold offsets\n"
        "offsets = np.load(os.path.join(DATASET_ROOT, 'thresholds.npy'))\n"
        "preds = np.argmax(probs + offsets, axis=1)\n"
        "print('Applied threshold offsets:', offsets.round(4).tolist())\n"
        "\n"
        "sub = pd.DataFrame({'ID': test['ID'], 'target': preds})\n"
        "sub.to_csv('submission.csv', index=False)\n"
        "print(f'submission.csv: {len(sub)} rows')\n"
        "print(sub['target'].value_counts().sort_index().to_string())\n"
    )

    infer_cell = _cell(infer_code)

    validate_cell = _cell(
        "import pandas as pd\n"
        "sub = pd.read_csv('submission.csv')\n"
        "assert {'ID', 'target'}.issubset(sub.columns)\n"
        "assert sub['target'].between(0, 6).all(), 'Targets out of range'\n"
        "print(f'OK — {len(sub)} rows')\n"
        "sub.head()\n"
    )

    cells = [cell0, cell1, mkdir_cell] + src_cells + [infer_cell, validate_cell]
    out_path = os.path.join(rerank_exp_dir, "notebook_inference.ipynb")
    return _make_notebook(cells, out_path)


def _make_notebook(cells: list, out_path: str) -> str:
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.0"},
        },
        "cells": cells,
    }
    with open(out_path, "w") as f:
        json.dump(notebook, f, indent=1)
    return out_path


def generate_transformer_notebook(exp_dir: str) -> str:
    """
    Generate a self-contained Kaggle training notebook for a transformer experiment.

    The notebook trains from scratch on Kaggle GPU using the saved config.
    BERTimbau (and other HuggingFace models) must be attached via Kaggle Models hub
    — see the instruction cell inside the notebook.

    Raises FileNotFoundError if the experiment hasn't been trained yet.
    """
    model_dir = os.path.join(exp_dir, "model")
    if not os.path.isdir(model_dir):
        raise FileNotFoundError(
            f"No trained transformer model found at {model_dir}. "
            "Run training first: python run.py configs/<name>.yaml --train"
        )

    config_path = os.path.join(exp_dir, "config.yaml")
    import yaml
    with open(config_path) as f:
        config = yaml.safe_load(f)

    exp_name  = config.get("experiment_name", os.path.basename(exp_dir))
    notes     = config.get("notes", "")
    pretrained = config["model"]["pretrained"]

    # ── Cell 0: markdown header ──────────────────────────────────────────────
    cell0 = _cell("\n".join([
        f"# {exp_name}",
        "",
        f"**Notes:** {notes}" if notes else "",
        "",
        "Auto-generated Kaggle submission notebook for a transformer experiment.",
        "Trains from scratch on Kaggle GPU and writes `submission.csv`.",
        "",
        "## Setup checklist",
        "1. **Accelerator**: GPU T4×2 (or P100) — *Notebook settings → Accelerator*",
        "2. **Internet**: Off at submission time",
        "3. **Dataset**: attach `spr-2026-mammography-report-classification` competition data",
        f"4. **Model weights**: attach `{pretrained}` via *Add-ons → Models*",
        "   - Search the Kaggle Models hub for the model name",
        "   - Update `PRETRAINED_PATH` in the config cell below to the mount path",
        "   - Local HuggingFace ID works when internet is ON (testing only)",
    ]), cell_type="markdown")

    # ── Cell 1: install deps ─────────────────────────────────────────────────
    cell1 = _cell(
        "import subprocess, sys\n"
        "subprocess.check_call([\n"
        "    sys.executable, '-m', 'pip', 'install', '-q',\n"
        "    'transformers>=4.40', 'accelerate>=0.27', 'sentencepiece>=0.1.99',\n"
        "    'pyyaml>=6.0', 'tqdm>=4.65', 'scikit-learn>=1.3',\n"
        "    'pandas>=2.0', 'numpy>=1.24',\n"
        "])\n"
    )

    # ── Cell 2: mkdir ────────────────────────────────────────────────────────
    mkdir_cell = _cell(
        "import os\n"
        "os.makedirs('src/models', exist_ok=True)\n"
        "os.makedirs('configs', exist_ok=True)\n"
        "os.makedirs('experiments', exist_ok=True)\n"
    )

    # ── Cells 3–N: embed src/ files ──────────────────────────────────────────
    src_cells = [
        _writefile_cell(p) for p in _TRANSFORMER_SRC_FILES if os.path.exists(p)
    ]

    # ── Config cell: write config, with pretrained path instruction ──────────
    import copy
    kaggle_config = copy.deepcopy(config)
    kaggle_config["wandb"] = {"enabled": False}   # no W&B credentials on Kaggle
    kaggle_config["gpu"] = "all"                   # use both T4s

    config_str = yaml.dump(kaggle_config, default_flow_style=False, sort_keys=False)
    config_dest = f"configs/{exp_name}.yaml"

    # Write config via %%writefile (no escaping issues), then patch pretrained path
    writefile_config_cell = _cell(f"%%writefile {config_dest}\n{config_str}")

    config_cell = _cell(
        "# ── Model path ──────────────────────────────────────────────────────\n"
        "# Auto-detects the correct subdirectory containing config.json.\n"
        "# Falls back to HuggingFace ID when internet is ON (local testing).\n"
        "import os\n"
        "\n"
        "_KAGGLE_MODEL_ROOT = '/kaggle/input/models/caokhoihuynh/bert-base-portuguese-cased/pytorch/default/1'\n"
        f"_HF_ID = {pretrained!r}\n"
        "\n"
        "def _find_model_path(root, hf_id):\n"
        "    \"\"\"Walk root to find the dir containing config.json; fall back to hf_id.\"\"\"\n"
        "    if os.path.isdir(root):\n"
        "        for dirpath, _, files in os.walk(root):\n"
        "            if 'config.json' in files:\n"
        "                print(f'Found model at: {dirpath}')\n"
        "                return dirpath\n"
        "        print(f'WARNING: config.json not found under {root}, using HF id')\n"
        "    return hf_id\n"
        "\n"
        "PRETRAINED_PATH = _find_model_path(_KAGGLE_MODEL_ROOT, _HF_ID)\n"
        "print(f'PRETRAINED_PATH = {PRETRAINED_PATH}')\n"
        "\n"
        "import yaml\n"
        f"with open({config_dest!r}) as f:\n"
        "    config = yaml.safe_load(f)\n"
        "config['model']['pretrained'] = PRETRAINED_PATH\n"
        f"with open({config_dest!r}, 'w') as f:\n"
        "    yaml.dump(config, f, default_flow_style=False, sort_keys=False)\n"
        f"print('Config written →', {config_dest!r})\n"
    )

    # ── Training + prediction cell ───────────────────────────────────────────
    train_cell = _cell(
        "import os, shutil\n"
        "from src.train_transformer import run_training_transformer\n"
        "from src.predict import run_predict_transformer\n"
        "\n"
        f"exp_dir = run_training_transformer({config_dest!r})\n"
        "run_predict_transformer(exp_dir)\n"
        "\n"
        "shutil.copy(os.path.join(exp_dir, 'submission.csv'), 'submission.csv')\n"
        "print('submission.csv ready at', os.getcwd())\n"
    )

    # ── Validation cell ──────────────────────────────────────────────────────
    validate_cell = _cell(
        "import pandas as pd\n"
        "sub = pd.read_csv('submission.csv')\n"
        "assert {'ID', 'target'}.issubset(sub.columns)\n"
        "assert sub['target'].between(0, 6).all(), 'Targets out of range'\n"
        "print(f'submission.csv: {len(sub)} rows')\n"
        "print(sub['target'].value_counts().sort_index().to_string())\n"
        "sub.head()\n"
    )

    cells = [cell0, cell1, mkdir_cell] + src_cells + [writefile_config_cell, config_cell, train_cell, validate_cell]
    out_path = os.path.join(exp_dir, "notebook.ipynb")
    return _make_notebook(cells, out_path)
