"""
Generate a self-contained Kaggle submission notebook from a trained experiment.

Each src/ file is written as a %%writefile cell — fully human-readable in Kaggle's
notebook viewer, no encoding/decoding. The notebook is completely self-contained:
upload the single .ipynb file, attach the competition dataset, run all cells.

Usage (via run.py):
    python run.py configs/expNNN.yaml --notebook
"""
import json
import os

# src/ files to embed, in import-dependency order
_SRC_FILES = [
    "src/__init__.py",
    "src/data.py",
    "src/features.py",
    "src/evaluate.py",
    "src/threshold.py",
    "src/logging_utils.py",
    "src/models/__init__.py",
    "src/models/linear.py",
    "src/train.py",
    "src/predict.py",
]


def _cell(source: str, cell_type: str = "code") -> dict:
    lines = source.splitlines(keepends=True)
    # ensure final newline
    if lines and not lines[-1].endswith("\n"):
        lines[-1] += "\n"
    return {
        "cell_type": cell_type,
        "metadata": {},
        "source": lines,
        **({"outputs": [], "execution_count": None} if cell_type == "code" else {}),
    }


def _writefile_cell(rel_path: str) -> dict:
    """Return a code cell that writes rel_path to disk.
    Non-empty files use %%writefile (human-readable); empty files use open().write('').
    """
    with open(rel_path, "r", encoding="utf-8") as f:
        content = f.read()
    if not content.strip():
        # %%writefile errors on an empty cell body — use plain Python instead
        return _cell(f"open({rel_path!r}, 'w').close()  # empty init file\n")
    source = f"%%writefile {rel_path}\n{content}"
    return _cell(source)


def generate_notebook(exp_dir: str) -> str:
    """
    Generate experiments/<exp>/notebook.ipynb from a trained experiment dir.
    Raises FileNotFoundError if the model hasn't been trained yet.
    """
    model_path = os.path.join(exp_dir, "model.pkl")
    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"No trained model found at {model_path}. "
            "Run training first: python run.py configs/<name>.yaml --train"
        )

    config_path = os.path.join(exp_dir, "config.yaml")
    import yaml
    with open(config_path) as f:
        config = yaml.safe_load(f)

    exp_name = config.get("experiment_name", os.path.basename(exp_dir))
    notes    = config.get("notes", "")

    # ── Cell 0: Markdown header ──────────────────────────────────────────────
    header = [f"# {exp_name}\n"]
    if notes:
        header.append(f"\n**Notes:** {notes}\n")
    header += [
        "\nThis notebook was auto-generated by `src/notebook_gen.py`.\n",
        "Run all cells to train from scratch and produce `submission.csv`.\n",
    ]
    cell0 = _cell("".join(header), cell_type="markdown")

    # ── Cell 1: Install dependencies ─────────────────────────────────────────
    cell1 = _cell(
        "import subprocess, sys\n"
        "subprocess.check_call([\n"
        "    sys.executable, '-m', 'pip', 'install', '-q',\n"
        "    'pyyaml>=6.0', 'tqdm>=4.65', 'scikit-learn>=1.3',\n"
        "    'pandas>=2.0', 'numpy>=1.24', 'scipy>=1.11',\n"
        "])\n"
    )

    # ── Cells 2–N: %%writefile one cell per src/ file ────────────────────────
    # Create src/models/ dir before writing models files (%%writefile won't mkdir)
    mkdir_cell = _cell(
        "import os\n"
        "os.makedirs('src/models', exist_ok=True)\n"
    )

    src_cells = []
    for rel_path in _SRC_FILES:
        if os.path.exists(rel_path):
            src_cells.append(_writefile_cell(rel_path))

    # ── Config + training cell ────────────────────────────────────────────────
    with open(config_path) as f:
        config_str = f.read()
    config_dest = f"configs/{exp_name}.yaml"
    train_cell = _cell(
        "import os, shutil\n"
        "os.makedirs('configs', exist_ok=True)\n"
        f"open({config_dest!r}, 'w').write({json.dumps(config_str)})\n"
        "\n"
        "from src.train import run_training\n"
        "from src.predict import run_predict\n"
        f"exp_dir = run_training({config_dest!r})\n"
        "run_predict(exp_dir)\n"
        "\n"
        "# Kaggle requires submission.csv at the working directory root\n"
        "shutil.copy(os.path.join(exp_dir, 'submission.csv'), 'submission.csv')\n"
        "print('submission.csv copied to', os.getcwd())\n"
    )

    # ── Validation cell ───────────────────────────────────────────────────────
    validate_cell = _cell(
        "import pandas as pd, os\n"
        "sub_path = os.path.join(exp_dir, 'submission.csv')\n"
        "sub = pd.read_csv(sub_path)\n"
        "assert {'ID', 'target'}.issubset(sub.columns), f'Bad columns: {sub.columns.tolist()}'\n"
        "assert sub['target'].between(0, 6).all(), 'Targets out of range 0-6'\n"
        "print(f'submission.csv looks good: {len(sub)} rows')\n"
        "print(sub['target'].value_counts().sort_index().to_string())\n"
        "sub.head()\n"
    )

    cells = [cell0, cell1, mkdir_cell] + src_cells + [train_cell, validate_cell]

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.10.0"},
        },
        "cells": cells,
    }

    out_path = os.path.join(exp_dir, "notebook.ipynb")
    with open(out_path, "w") as f:
        json.dump(notebook, f, indent=1)

    return out_path
